
<!DOCTYPE html>
<html>
<head>
	<title>Simple contact form with attachment</title>
</head>
	<body>

		<? 
		   if (!empty($errors)) {
		   	 foreach ($errors as &$error) { 
		?>
				<div class="error"><?php isset($error) ?></div>
		<?   }
		   }
		?>

		<form action="." method="post" enctype="multipart/form-data">
			<div>
				<label for="name">Your name:</label>
				<input type="text" name="name" value="<?php isset($contactForm->name) ?>" id="name" required>
			</div>
			<div>
				<label for="email">Your email:</label>
				<input type="email" name="email" value="<?php isset($contactForm->email) ?>" id="email" required>
			</div>
			<div>
				<label for="message">Your message:</label>
				<textarea name="message" id="message" required><?php isset($contactForm->message) ?></textarea>
			</div>
			<div>
				<label for="attachment">Attachment:</label>
				<input type="file" id="attachment" name="attachment">
			</div>
			<div>
				<input type="submit" value="Send Message!">
			</div>
		</form>
	</body>
</html>


